# Generated by Django 6.0.7 on 2026-08-02 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('commission_15', models.IntegerField()),
                ('driver_earnings', models.IntegerField()),
                ('collection_reference_id', models.UUIDField(blank=True, null=True)),
                ('collection_status', models.CharField(default='PENDING', max_length=20)),
                ('disbursement_reference_id', models.UUIDField(blank=True, null=True)),
                ('disbursement_status', models.CharField(default='PENDING', max_length=20)),
                ('momo_txn_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
        ),
    ]
