# Generated by Django 6.0.7 on 2026-08-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drivers_needed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
